export const CREATE_PRODUCT_LOADING = 'CREATE_PRODUCT_LOADING';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';

export const DELETE_PRODUCT_LOADING = 'DELETE_PRODUCT_LOADING';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const OPEN_OR_CLOSE_MODAL = 'OPEN_OR_CLOSE_MODAL';

export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const GET_MORE_PRODUCTS = 'GET_MORE_PRODUCTS';

