export const CREATE_PRODUCT_LOADING = 'CREATE_PRODUCT_LOADING';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';

export const DELETE_PRODUCT_LOADING = 'DELETE_PRODUCT_LOADING';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const OPEN_OR_CLOSE_MODAL = 'OPEN_OR_CLOSE_MODAL';

export const SORT_MOST_EXPENSIVE_PRODUCTS = 'SORT_MOST_EXPENSIVE_PRODUCTS';
export const SORT_CHEAPEST_PRODUCTS = 'SORT_CHEAPEST_PRODUCTS';
export const SORT_NEWEST_PRODUCTS = 'SORT_NEWEST_PRODUCTS';

